---
version: '1.1'

services:

  app:
    image:  app
    container_name: app
    build:
      dockerfile: Dockerfile
    restart:  always
    ports:
      - "5000:5000"
    depends_on:
      - "db"

  db:
    image:  mariadb
    restart:  always
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=superstrongpassword
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=lahaus
      - MYSQL_USER=lahaus
    volumes:
      - data:/var/lib/mysql

volumes:
  data:
