---
version: '2.0'

services:

  app:
    image:  app
    restart:  always
    container_name: app
    build:
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DATABASE_ENDPOINT=db
      - DATABASE_DB_NAME=lahaus
      - DATABASE_USER_NAME=lahaus
      - DATABASE_USER_PASSWORD=password
    depends_on:
      - "db"

  db:
    image:  mariadb
    restart:  always
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=superstrongpassword
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=lahaus
      - MYSQL_USER=lahaus
    volumes:
      - data:/var/lib/mysql

volumes:
  data:
