---
version: '2.0'

services:

  app:
    image:  app
    restart:  always
    container_name: app
    build:
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - "DATABASE_ENDPOINT=db:3306"
      - "DATABASE_DB_NAME=ushuhuch"
      - "DATABASE_USER_NAME=voyephoo"
      - "DATABASE_USER_PASSWORD=r1SYCVOGZThrBjb0jYWoHRNz2yjhPcpVSvOHQRqQ"
    depends_on:
      - "db"

  db:
    image:  mariadb
    restart:  always
    container_name: db
    environment:
      - "MYSQL_ROOT_PASSWORD=superstrongpassword"
      - "MYSQL_PASSWORD=r1SYCVOGZThrBjb0jYWoHRNz2yjhPcpVSvOHQRqQ"
      - "MYSQL_DATABASE=ushuhuch"
      - "MYSQL_USER=voyephoo"
    volumes:
      - "data:/var/lib/mysql"

volumes:
  data:
